### ISSUE TITLE
oasis deploy errors

### ISSUE THREAD

**Issue by rjgeek** [oasislabs/tutorials#57]
**Version**
root@9c4ef8afa73b:~/tutorials/hello-world/app# npm -v  
6.12.0
root@9c4ef8afa73b:~/tutorials/hello-world/app# node -v
v8.16.2

**Errors**
root@9c4ef8afa73b:~/tutorials/hello-world/app# oasis deploy
   Deploying hello-world

> hello-world@1.0.0 deploy /root/tutorials/hello-world/app
> node scripts/deploy_service.js

WARNING: Missing strong random number source; using weak randomBytes
Warning: XMLHttpRequest is not defined
/root/tutorials/hello-world/app/scripts/deploy_service.js:16
  .finally(() => {
          ^

TypeError: oasis.workspace.HelloWorld.deploy(...).then(...).catch(...).finally is not a function
    at Object.<anonymous> (/root/tutorials/hello-world/app/scripts/deploy_service.js:16:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@1.0.0 deploy: `node scripts/deploy_service.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-world@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-16T23_01_29_807Z-debug.log
error: process `npm` exited with code `1`

**Comment by rjgeek** [comment]
it works in the node version 
v10.16.3

**Comment by nhynes** [comment]
Cool, thanks for asking and answering this question! Yes, we're only targeting the current LTS for now.
